/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Requests;

import model.Areas.Area;
import model.EcoSystem;
import java.awt.CardLayout;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JPanel;


/**
 *
 * @author dhruv
 */
public class UpdateRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateRequestJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecoSystem;
    List<String> a = new ArrayList<>();

    public UpdateRequestJPanel(JPanel userProcessContainer, EcoSystem ecoSystem, String reqId, String personName, String location, String area, String typeOfEmergency, String comments, String dateTimeStamp, String hosp, String fireDept, String policeDept, String shelter, String status) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        statusDD.addItem("Active");
        statusDD.addItem("Assigned");
        statusDD.addItem("Completed");

        setData(reqId, personName, location, area, typeOfEmergency, comments, dateTimeStamp, hosp, fireDept, policeDept, shelter, status);

        getAreas(area);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        entityNameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        entityLocationField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        entityAreaField = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        entityTypeOfEmergency = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        commentsField = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        statusDD = new javax.swing.JComboBox<>();
        lblReqID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblSelectedHos = new javax.swing.JLabel();
        lblSelectedPD = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblSelectedFD = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblSelectedShel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnProceed = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbltimestamp = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        add(entityNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 191, -1));

        jLabel3.setText("Location");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        entityLocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entityLocationFieldActionPerformed(evt);
            }
        });
        add(entityLocationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 191, -1));

        jLabel8.setText("Area");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        add(entityAreaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 191, -1));

        jLabel6.setText("Selected Item");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));
        add(entityTypeOfEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 277, 17));

        jLabel7.setText("Comments for Dispatched Units");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        commentsField.setColumns(20);
        commentsField.setRows(5);
        jScrollPane2.setViewportView(commentsField);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 277, -1));

        jLabel5.setText("Status");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        statusDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusDDActionPerformed(evt);
            }
        });
        add(statusDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 277, -1));

        lblReqID.setText("jLabel9");
        add(lblReqID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel9.setText("Selected Hospital");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        lblSelectedHos.setText("jLabel10");
        add(lblSelectedHos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 274, -1));

        lblSelectedPD.setText("jLabel10");
        add(lblSelectedPD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 274, -1));

        jLabel10.setText("Selected Police Department");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        lblSelectedFD.setText("jLabel10");
        add(lblSelectedFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 274, -1));

        jLabel11.setText("Selected Fire Department");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, -1, -1));

        lblSelectedShel.setText("jLabel10");
        add(lblSelectedShel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 274, -1));

        jLabel12.setText("Selected Shelter ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        btnProceed.setText("Proceed");
        btnProceed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProceedActionPerformed(evt);
            }
        });
        add(btnProceed, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(119, 10, 40));
        jLabel4.setText("Update Request");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 170, 30));

        jLabel14.setText("RequestID:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lbltimestamp.setText("jLabel1");
        add(lbltimestamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void entityLocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entityLocationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entityLocationFieldActionPerformed

    private void statusDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusDDActionPerformed

    private void btnProceedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProceedActionPerformed
        // TODO add your handling code here:
        String entityName = entityNameField.getText();
        String entityLocation = entityLocationField.getText();
        String entityArea = entityAreaField.getSelectedItem().toString();
        String typeOfEmergency = entityTypeOfEmergency.getText();
        String comments = commentsField.getText();
        String status = statusDD.getSelectedItem().toString();
        String timeStamp = lbltimestamp.getText();
        UnitsJpanel unitsPanel = new UnitsJpanel(userProcessContainer, ecoSystem, entityName, entityLocation, entityArea, typeOfEmergency, comments,timeStamp, status);
        userProcessContainer.add("manageDelJPanel", unitsPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnProceedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnProceed;
    private javax.swing.JTextArea commentsField;
    private javax.swing.JComboBox<String> entityAreaField;
    private javax.swing.JTextField entityLocationField;
    private javax.swing.JTextField entityNameField;
    private javax.swing.JLabel entityTypeOfEmergency;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblReqID;
    private javax.swing.JLabel lblSelectedFD;
    private javax.swing.JLabel lblSelectedHos;
    private javax.swing.JLabel lblSelectedPD;
    private javax.swing.JLabel lblSelectedShel;
    private javax.swing.JLabel lbltimestamp;
    private javax.swing.JComboBox<String> statusDD;
    // End of variables declaration//GEN-END:variables

    private void setData(String reqId, String personName, String location, String area, String typeOfEmergency, String comments, String dateTimeStamp, String hosp, String fireDept, String policeDept, String shelter, String status) {
        lblReqID.setText(reqId);
        entityNameField.setText(personName);
        entityLocationField.setText(location);
        entityAreaField.setSelectedItem(area);
        entityTypeOfEmergency.setText(typeOfEmergency);
        commentsField.setText(comments);
        int currIndex = 0;
        switch (status) {
            case "Active":
                currIndex = 0;
                break;
            case "Assigned":
                currIndex = 1;
                break;
            case "Completed":
                currIndex = 2;
                break;
            default:
                currIndex = 0;
        }
        statusDD.setSelectedIndex(currIndex);
        lblSelectedHos.setText(hosp);
        lblSelectedPD.setText(policeDept);
        lblSelectedFD.setText(fireDept);
        lblSelectedShel.setText(shelter);

    }


    private void getAreas(String area) {
        for (Area a : ecoSystem.getAreaDirectory().getAreasList()) {
            entityAreaField.addItem(a.getAreaName() + " " + a.getAreaZipCode());
            if (a.getAreaName().equalsIgnoreCase(area)) {
                entityAreaField.setSelectedItem(a.getAreaName() + " " + a.getAreaZipCode());
            }

        }
    }
}
