/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.HospitalDepartment;

import model.EcoSystem;
import model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import UI.HospitalDepartment.CriticalCaseManagementJPanel;

/**
 *
 * @author shreyansipatel
 */
public class PatientManagementJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount account;

    public PatientManagementJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, String patientName, String area, String status, String reqID, String docName, String npiNum, String ambNum) {
        initComponents();

        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        btnAdmitCritical.setVisible(false);
        btnAdmitGeneral.setVisible(false);
        btnAdmitCriticalWard.setVisible(false);
        lblCovidStatus.setVisible(false);
        rdPositive.setVisible(false);
        rdNegative.setVisible(false);

        ButtonGroup critical = new ButtonGroup();
        critical.add(rdYes);
        critical.add(rdNo);

        ButtonGroup covid = new ButtonGroup();
        covid.add(rdPositive);
        covid.add(rdNegative);

        setData(patientName, area, status, reqID, docName, npiNum, ambNum);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdYes = new javax.swing.JRadioButton();
        lblSelectEmergency = new javax.swing.JLabel();
        rdNo = new javax.swing.JRadioButton();
        rdPositive = new javax.swing.JRadioButton();
        rdNegative = new javax.swing.JRadioButton();
        lblCovidStatus = new javax.swing.JLabel();
        btnAdmitCritical = new javax.swing.JButton();
        btnAdmitCriticalWard = new javax.swing.JButton();
        btnAdmitGeneral = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblDisplayPatientName = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblDisplayPatientArea = new javax.swing.JLabel();
        lblDisplayStatus = new javax.swing.JLabel();
        lblPatientArea = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblDisplayRequestId = new javax.swing.JLabel();
        lblRequestId = new javax.swing.JLabel();
        lblEMTName = new javax.swing.JLabel();
        lblAmbNum = new javax.swing.JLabel();
        lblNPINum = new javax.swing.JLabel();
        lblDisplayEMTName = new javax.swing.JLabel();
        lblDisplayAmbNum = new javax.swing.JLabel();
        lblDisplayNPINum = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdYes.setText("Yes");
        rdYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdYesActionPerformed(evt);
            }
        });
        add(rdYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        lblSelectEmergency.setText("Emergency Case / Aged above 70 or below 5?");
        add(lblSelectEmergency, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        rdNo.setText("No");
        rdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNoActionPerformed(evt);
            }
        });
        add(rdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        rdPositive.setText("Tested Positive");
        rdPositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPositiveActionPerformed(evt);
            }
        });
        add(rdPositive, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));

        rdNegative.setText("Tested Negative");
        rdNegative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNegativeActionPerformed(evt);
            }
        });
        add(rdNegative, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        lblCovidStatus.setText("Covid Status :");
        add(lblCovidStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        btnAdmitCritical.setText("Admit in Critical Ward");
        btnAdmitCritical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmitCriticalActionPerformed(evt);
            }
        });
        add(btnAdmitCritical, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        btnAdmitCriticalWard.setText("Admit in Critical Ward");
        btnAdmitCriticalWard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmitCriticalWardActionPerformed(evt);
            }
        });
        add(btnAdmitCriticalWard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, -1));

        btnAdmitGeneral.setText("Admit in General Ward");
        btnAdmitGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmitGeneralActionPerformed(evt);
            }
        });
        add(btnAdmitGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        lblTitle.setText("Admit Patient in Critical/General Ward");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 30));

        lblDisplayPatientName.setText("jLabel6");
        add(lblDisplayPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        lblPatientName.setText("Patient Name :");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, -1));

        lblDisplayPatientArea.setText("jLabel8");
        add(lblDisplayPatientArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        lblDisplayStatus.setText("jLabel8");
        add(lblDisplayStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        lblPatientArea.setText("Patient Area :");
        add(lblPatientArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        lblStatus.setText("Status :");
        add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, -1));

        lblDisplayRequestId.setText("jLabel8");
        add(lblDisplayRequestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        lblRequestId.setText("Request ID :");
        add(lblRequestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        lblEMTName.setText("EMT Technician Name:");
        add(lblEMTName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        lblAmbNum.setText("Ambulance number:");
        add(lblAmbNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        lblNPINum.setText("NPI Number:");
        add(lblNPINum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        lblDisplayEMTName.setText("jLabel13");
        add(lblDisplayEMTName, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        lblDisplayAmbNum.setText("jLabel14");
        add(lblDisplayAmbNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        lblDisplayNPINum.setText("jLabel15");
        add(lblDisplayNPINum, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rdYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdYesActionPerformed
        // TODO add your handling code here:
        btnAdmitCritical.setVisible(true);

    }//GEN-LAST:event_rdYesActionPerformed

    private void rdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNoActionPerformed
        // TODO add your handling code here:

        if (rdNo.isSelected()) {
            lblCovidStatus.setVisible(true);
            rdPositive.setVisible(true);
            rdNegative.setVisible(true);

        }
    }//GEN-LAST:event_rdNoActionPerformed

    private void rdPositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdPositiveActionPerformed
        // TODO add your handling code here:
        btnAdmitCriticalWard.setVisible(true);


    }//GEN-LAST:event_rdPositiveActionPerformed

    private void rdNegativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNegativeActionPerformed
        // TODO add your handling code here:
        btnAdmitGeneral.setVisible(true);
    }//GEN-LAST:event_rdNegativeActionPerformed

    private void btnAdmitCriticalWardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmitCriticalWardActionPerformed
        // TODO add your handling code here:
        
        String patientName = lblDisplayPatientName.getText();
        String area = lblDisplayPatientArea.getText();
        String status = lblDisplayStatus.getText();
        String reqID = lblDisplayRequestId.getText();
        String docName = lblDisplayEMTName.getText();
        String npiNum = lblDisplayNPINum.getText();
        String ambNum = lblDisplayAmbNum.getText();
        
        CriticalCaseManagementJPanel manageCritical = new CriticalCaseManagementJPanel(userProcessContainer, account, system, patientName, area, status, reqID, docName, npiNum, ambNum);
        userProcessContainer.add("Manage Critical Patients", manageCritical);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdmitCriticalWardActionPerformed

    private void btnAdmitCriticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmitCriticalActionPerformed
        // TODO add your handling code here:
        
        String patientName = lblDisplayPatientName.getText();
        String area = lblDisplayPatientArea.getText();
        String status = lblDisplayStatus.getText();
        String reqID = lblDisplayRequestId.getText();
        String docName = lblDisplayEMTName.getText();
        String npiNum = lblDisplayNPINum.getText();
        String ambNum = lblDisplayAmbNum.getText();
        
        CriticalCaseManagementJPanel manageCriticalCase = new CriticalCaseManagementJPanel(userProcessContainer, account, system, patientName, area, status, reqID, docName, npiNum, ambNum);
        userProcessContainer.add("Manage Critical Patients", manageCriticalCase);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdmitCriticalActionPerformed

    private void btnAdmitGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmitGeneralActionPerformed
        // TODO add your handling code here:
        
        String patientName = lblDisplayPatientName.getText();
        String area = lblDisplayPatientArea.getText();
        String status = lblDisplayStatus.getText();
        String reqID = lblDisplayRequestId.getText();
        String docName = lblDisplayEMTName.getText();
        String npiNum = lblDisplayNPINum.getText();
        String ambNum = lblDisplayAmbNum.getText();

        GeneralCaseManagementJPanel manageGeneralCase = new GeneralCaseManagementJPanel(userProcessContainer, account, system, patientName, area, status, reqID, docName, npiNum, ambNum);
        userProcessContainer.add("Manage General Patients", manageGeneralCase);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdmitGeneralActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmitCritical;
    private javax.swing.JButton btnAdmitCriticalWard;
    private javax.swing.JButton btnAdmitGeneral;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAmbNum;
    private javax.swing.JLabel lblCovidStatus;
    private javax.swing.JLabel lblDisplayAmbNum;
    private javax.swing.JLabel lblDisplayEMTName;
    private javax.swing.JLabel lblDisplayNPINum;
    private javax.swing.JLabel lblDisplayPatientArea;
    private javax.swing.JLabel lblDisplayPatientName;
    private javax.swing.JLabel lblDisplayRequestId;
    private javax.swing.JLabel lblDisplayStatus;
    private javax.swing.JLabel lblEMTName;
    private javax.swing.JLabel lblNPINum;
    private javax.swing.JLabel lblPatientArea;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRequestId;
    private javax.swing.JLabel lblSelectEmergency;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rdNegative;
    private javax.swing.JRadioButton rdNo;
    private javax.swing.JRadioButton rdPositive;
    private javax.swing.JRadioButton rdYes;
    // End of variables declaration//GEN-END:variables

    private void setData(String patientName, String area, String status, String reqID, String docName, String npiNum, String ambNum) {
        lblDisplayPatientName.setText(patientName);
        lblDisplayPatientArea.setText(area);
        lblDisplayStatus.setText(status);
        lblDisplayRequestId.setText(reqID);
        lblDisplayEMTName.setText(docName);
        lblDisplayAmbNum.setText(npiNum);
        lblDisplayNPINum.setText(ambNum);
    }
}
