/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.FireDepartment;

import model.EcoSystem;
import model.Requests.Request;
import model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author siddh
 */
public class FactoryFireMang extends javax.swing.JPanel {

    /**
     * Creates new form FactoryFireMang
     */
    
    private JPanel userProcessContainer;

    private UserAccount account;
   
    EcoSystem system;
    public FactoryFireMang(JPanel userProcessContainer, UserAccount account,EcoSystem system, String funit, String reqID) {
        initComponents();
        this.account=account;
    this.userProcessContainer = userProcessContainer;
    this.system=system;
    txtFU.setEditable(false);
    txtFU.setText(funit);
    lblReq.setText(reqID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblfactory = new javax.swing.JLabel();
        txtFU = new javax.swing.JTextField();
        lblReq = new javax.swing.JLabel();
        btnComp = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Factory Unit");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 110, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 110, 30));

        lblfactory.setText("Fire Unit Dispatched is :");
        add(lblfactory, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 20));
        add(txtFU, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 140, -1));

        lblReq.setText("jLabel9");
        add(lblReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        btnComp.setBackground(new java.awt.Color(153, 255, 102));
        btnComp.setText("Complete");
        btnComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompActionPerformed(evt);
            }
        });
        add(btnComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompActionPerformed
        // TODO add your handling code here:
        System.out.println("reqID" + lblReq.getText());
        for (Request j : system.getRequestDirectory().getRequests()) {
            if (j.getRequestId() == lblReq.getText()) {

                j.setStatus("Completed");
                j.setEntityDesc("RFU " + txtFU.getText());
                JOptionPane.showMessageDialog(null, "Unit has been dispatched");

            }
        }
    }//GEN-LAST:event_btnCompActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblReq;
    private javax.swing.JLabel lblfactory;
    private javax.swing.JTextField txtFU;
    // End of variables declaration//GEN-END:variables
}
