/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PoliceDepartment;

import model.EcoSystem;
import model.PoliceDepartment.ControlUnitDirectory;
import model.PoliceDepartment.ControlUnit;
import model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author dhruv
 */
public class AddControlUnitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddControlUnitJPanel
     */
        private JPanel userProcessContainer;
        private UserAccount account;
        EcoSystem system;
        String reqID = "";

    AddControlUnitJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem system, String reqID) {
        initComponents();
         this.account=account;
        this.userProcessContainer = userProcessContainer;
        this.system=system;
        reqID = reqID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblCUNum = new javax.swing.JLabel();
        txtCUNum = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblTCNum = new javax.swing.JLabel();
        txtTCNum = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 30));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 40, -1, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        lblTitle.setText("Add New Control Unit");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 270, -1));

        lblCUNum.setText("Control Unit Number :");
        add(lblCUNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 20));
        add(txtCUNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, -1));

        btnAdd.setText("Create");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        lblTCNum.setText("Traffic Control Unit:");
        add(lblTCNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));
        add(txtTCNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     String ccuNum = txtCUNum.getText();
     String tcuNum = txtTCNum.getText();
     
     ControlUnitDirectory ccuDir = system.getControlUnitDirectory();
     ControlUnit cu = null;
     if (system.getControlUnitDirectory() == null){
         cu = new ControlUnit(ccuNum,tcuNum);
         ccuDir.getControlUnit().add(cu);
     } else {
         cu = system.getControlUnitDirectory().createCUDirectory(ccuNum,tcuNum);
     }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCUNum;
    private javax.swing.JLabel lblTCNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCUNum;
    private javax.swing.JTextField txtTCNum;
    // End of variables declaration//GEN-END:variables

//    private void populatePD() {
//       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
}
