/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.PoliceDepartment;

import model.EcoSystem;
import model.PoliceDepartment.ControlUnit;
import model.Requests.Request;
import model.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author dhruv
 */
public class AssignControlUnitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignControlUnitJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    EcoSystem ecosystem;

    public AssignControlUnitJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem ecosystem, String reqID) {
        initComponents();
        this.account = account;
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        lblReqID.setText(reqID);
        getControlUnit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblControlUnit = new javax.swing.JLabel();
        cmbControlUnit = new javax.swing.JComboBox<>();
        btnContinue = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblReqID = new javax.swing.JLabel();
        lblRequestID = new javax.swing.JLabel();
        lblFinalCU = new javax.swing.JLabel();
        txtFinalCU = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblControlUnit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblControlUnit.setText("Select Critical Control unit to Dispatch");
        add(lblControlUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        cmbControlUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbControlUnitActionPerformed(evt);
            }
        });
        add(cmbControlUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, 20));

        btnContinue.setText("Continue");
        btnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinueActionPerformed(evt);
            }
        });
        add(btnContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        lblTitle.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        lblTitle.setText("Assign Control Unit");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 250, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 110, 30));
        add(lblReqID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, 20));

        lblRequestID.setText("Request ID:");
        add(lblRequestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        lblFinalCU.setText("Selected Control Unit");
        add(lblFinalCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        txtFinalCU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFinalCUActionPerformed(evt);
            }
        });
        add(txtFinalCU, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinueActionPerformed
        // TODO add your handling code here:
        //String CCUDiv = cmbControlUnit.getSelectedItem().toString();
        //txtFinalCU.setText(CCUDiv);
        System.out.println("reqID" + lblReqID.getText());
          for (Request j : ecosystem.getRequestDirectory().getRequests()) {
            if (j.getRequestId() == lblReqID.getText()) {                
                j.setStatus("Completed");
            }
        }
        PoliceDeptWorkAreaJPanel dvj = new PoliceDeptWorkAreaJPanel(userProcessContainer, account, ecosystem);
        userProcessContainer.add("Police Department Area", dvj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnContinueActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component c = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFinalCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFinalCUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFinalCUActionPerformed

    private void cmbControlUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbControlUnitActionPerformed
        // TODO add your handling code here:
        String CCUDiv = cmbControlUnit.getSelectedItem().toString();
        txtFinalCU.setText(CCUDiv);
    }//GEN-LAST:event_cmbControlUnitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnContinue;
    private javax.swing.JComboBox<String> cmbControlUnit;
    private javax.swing.JLabel lblControlUnit;
    private javax.swing.JLabel lblFinalCU;
    private javax.swing.JLabel lblReqID;
    private javax.swing.JLabel lblRequestID;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtFinalCU;
    // End of variables declaration//GEN-END:variables

    private void getControlUnit() {
        for (ControlUnit b : ecosystem.getControlUnitDirectory().getCcunits()) {
            cmbControlUnit.addItem(b.getControlUnit());
        }
    }

}
