/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.SystemAdmin;

import UI.Requests.CreateRequest;
import UI.Requests.ViewRequestsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.EcoSystem;
import model.UserAccount.UserAccount;

/**
 *
 * @author dhruv
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminworkArea
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount userAccount;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
//        populateTree();
    }
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecosystem){
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.userAccount = userAccount;
        System.out.println(userAccount.getRole());
        if ("model.Role.AdminRole".equals(userAccount.getRole().getClass().getName())) {
        lblRequestTitle.setVisible(false);
        btnCreateRequest.setVisible(false);  
        lblEnterpriseTitle.setVisible(false);
        btnManageHospital.setVisible(false);
        btnManagePolice.setVisible(false);
        btnManageFire.setVisible(false);
        btnManageShelter.setVisible(false);
        lblUserAdminTitle.setVisible(false);
        btnUsers.setVisible(false);
        btnAdmins.setVisible(false);
        btnAreaAdmins.setVisible(false);
        lblRequestTitle.setVisible(true);
        btnCreateRequest.setVisible(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        lblRequestTitle = new javax.swing.JLabel();
        btnCreateRequest = new javax.swing.JButton();
        lblEnterpriseTitle = new javax.swing.JLabel();
        btnManageShelter = new javax.swing.JButton();
        btnManagePolice = new javax.swing.JButton();
        btnManageHospital = new javax.swing.JButton();
        btnManageFire = new javax.swing.JButton();
        lblUserAdminTitle = new javax.swing.JLabel();
        btnUsers = new javax.swing.JButton();
        btnAdmins = new javax.swing.JButton();
        btnAreaAdmins = new javax.swing.JButton();
        btnManageRequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setText("Welcome to the System");
        add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 16, -1, -1));

        lblRequestTitle.setText("Click below button to Create and manage Requests:");
        add(lblRequestTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 58, -1, -1));

        btnCreateRequest.setText("Create Requests");
        btnCreateRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRequestActionPerformed(evt);
            }
        });
        add(btnCreateRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 86, 166, 48));

        lblEnterpriseTitle.setText("Create Enterprises with use of below Buttons:");
        add(lblEnterpriseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 165, -1, -1));

        btnManageShelter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/House.png"))); // NOI18N
        btnManageShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageShelterActionPerformed(evt);
            }
        });
        add(btnManageShelter, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 100, 100));

        btnManagePolice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Police.png"))); // NOI18N
        btnManagePolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePoliceActionPerformed(evt);
            }
        });
        add(btnManagePolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, 100));

        btnManageHospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hospital.png"))); // NOI18N
        btnManageHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospitalActionPerformed(evt);
            }
        });
        add(btnManageHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 199, 100, 100));

        btnManageFire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fire.png"))); // NOI18N
        btnManageFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFireActionPerformed(evt);
            }
        });
        add(btnManageFire, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 100, 100));

        lblUserAdminTitle.setText("Create user and admins with use of below buttons:");
        add(lblUserAdminTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 373, -1, -1));

        btnUsers.setText("Users");
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });
        add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 407, 164, 51));

        btnAdmins.setText("Admin");
        btnAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsActionPerformed(evt);
            }
        });
        add(btnAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 407, 114, 51));

        btnAreaAdmins.setText("Area Admin");
        btnAreaAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaAdminsActionPerformed(evt);
            }
        });
        add(btnAreaAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 407, 151, 51));

        btnManageRequest.setText("Manage Requests");
        btnManageRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageRequestActionPerformed(evt);
            }
        });
        add(btnManageRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 86, 166, 48));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 311, 62, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Police");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 62, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Shelter");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 62, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fire");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 62, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRequestActionPerformed
        // TODO add your handling code here:
        CreateRequest createRequest = new CreateRequest(userProcessContainer, ecosystem);
        userProcessContainer.add("createRequest", createRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateRequestActionPerformed

    private void btnManageShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageShelterActionPerformed
        // TODO add your handling code here:
        ManageShelterHomeJPanel manageShelter = new ManageShelterHomeJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageShelter);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageShelterActionPerformed

    private void btnManageFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFireActionPerformed
        // TODO add your handling code here:
        ManageFireDept manageFire = new ManageFireDept(userProcessContainer, ecosystem);
        userProcessContainer.add("managePoliceDepartmentJPanel", manageFire);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageFireActionPerformed

    private void btnManagePoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePoliceActionPerformed
        // TODO add your handling code here:
        ManagePoliceDepartmentJPanel managePolice = new ManagePoliceDepartmentJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("managePoliceDepartmentJPanel", managePolice);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePoliceActionPerformed

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        ManageUserJPanel manageUser = new ManageUserJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageUserJPanel", manageUser);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsActionPerformed
        // TODO add your handling code here:
        ManageAdminJPanel manageAdmin = new ManageAdminJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageAdmin);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAdminsActionPerformed

    private void btnAreaAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaAdminsActionPerformed
        // TODO add your handling code here:
        ManageAreaJPanel manageArea = new ManageAreaJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageArea);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAreaAdminsActionPerformed

    private void btnManageRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRequestActionPerformed
        // TODO add your handling code here:
        ViewRequestsJPanel manageArea = new ViewRequestsJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageArea);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRequestActionPerformed

    private void btnManageHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospitalActionPerformed
        // TODO add your handling code here:
        ManageHospitalDeptJPanel manageHospital = new ManageHospitalDeptJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageAdminJPanel", manageHospital);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHospitalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnAreaAdmins;
    private javax.swing.JButton btnCreateRequest;
    private javax.swing.JButton btnManageFire;
    private javax.swing.JButton btnManageHospital;
    private javax.swing.JButton btnManagePolice;
    private javax.swing.JButton btnManageRequest;
    private javax.swing.JButton btnManageShelter;
    private javax.swing.JButton btnUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEnterpriseTitle;
    private javax.swing.JLabel lblRequestTitle;
    private javax.swing.JLabel lblUserAdminTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
